### ISSUE TITLE
samsung.com in list?

### ISSUE THREAD

**Issue by nikitastasik** [7c/fakefilter#109]
Hi! 'samsung.com' is in list https://raw.githubusercontent.com/7c/fakefilter/refs/heads/main/txt/data.txt

It's strange

**Comment by 7c** [comment]
we will remove it, upset providers (tempr.email in this case) try to inject some stuff into our list, this is why we have introduced https://github.com/7c/fakefilter/issues/29 which covers 98% of regular email hosts, but sometimes we. need your help to cleanup. Since our system is fully automated it is not easy to detect them. Thanks for reporting.

**Comment by nikitastasik** [comment]
Thank you!
