### ISSUE TITLE
API Request - add a section to see if domaine is still valid

### ISSUE THREAD

**Issue by Daniel3356** [7c/fakefilter#32]
I was wondering if you could add to the API to possibility of being able to see if the somaine is still valid: 

This is the list of all disposable domain that was up and running: 

 ***
wifi-map.net
convoitucpa.com
mantutimaison.com
shhongshuhan.com
snasu.info
phonestlebuka.com
hungtaoteile.com
victorysvg.com
piribet100.com
oanhxintv.com
yongshuhan.com
toanciamobile.com
pfmretire.com
mantutivi.com
mamonsuka.com
hansgu.com
usbvap.com
hacktoy.com
ladz.site
cerapht.site
suprj.site
screalian.site
bookez.site
rtfat.site
syndonation.site
howtb.site
kaspecism.site
pdfrj.site
literc.site
azwen.site
foundents.site
refap.site
rtfie.site
qtxm.us
azwee.site
pubiy.site
bookue.site
rustracker.site
refal.site
omilk.site
pubis.site
devoi.site
how1z.site
coduh.site
zipzx.site
filezw.site
readoe.site
devou.site
rollercover.us
prcea.site
betration.site
bookug.site
1ki.co
supoz.site
zipea.site
txtee.site
codur.site
lahi.me
docxu.site
manau.site
readyx.site
pdfro.site
csht.team
suprd.site
plainst.site
devib.site
sproces.shop
***

Last check:
August 26, 2022

**Comment by ferreiro** [comment]
@Daniel3356 this is useful. How did you create that list?

**Comment by Daniel3356** [comment]
> @Daniel3356 this is useful. How did you create that list?

You can look at google domain (bulk registration) and see what domain can you buy. All the one that you can buy are no longer valid. 

from a software approach, you can still look at an A and MX record, if none of them are found you are 50% sure. Probably Google, NameCheap, Godady have an api for bulk domain registrations.

**Comment by ferreiro** [comment]
That's a good idea. I have a similar problem where I want to see if an email is really valid. Is the MX lookup accurate? Can anyone update the DNS and add fake registers or there is a way to validate that?

**Comment by 7c** [comment]
![image](https://user-images.githubusercontent.com/22910022/212379956-592cca8c-c2b7-4964-8502-10bd1ec086af.png)


The idea of the JSON formats firstseen and lastseen properties are to cleanup domains (https://github.com/7c/fakefilter/issues/6) - what do you guys think about this concept ? Everyone can have different concepts how to calculate a valid domain. 

We want to introduce new json format next weeks/months because single domain can be seen in multiple providers. As an example:'pfmretire.com' which has been seen at 4 different providers: 'mail-temp.com', 'generator.email','emailfake.com','email-fake.com'

**Comment by 7c** [comment]
the cleanup was implemented and detailed at #6 - thanks!
