### ISSUE TITLE
add domains to cryptogmail.com

### ISSUE THREAD

**Issue by sobolevdmitry** [7c/fakefilter#64]
Hi, I see that you already have cryptogmail.com, but you are missing some of their domains:

```
gotgel.org
jollyfree.com
rungel.net
```

You can easily verify that these domains really belong to them:
1. `https://cryptogmail.com/api/emails?inbox=a@gotgel.org`
2. `https://cryptogmail.com/api/emails?inbox=a@jollyfree.com`
3. `https://cryptogmail.com/api/emails?inbox=a@rungel.net`

If you specify a non-existent box (or not their domain), you will get a 404:
`https://cryptogmail.com/api/emails?inbox=a@gmail.com`

**Comment by 7c** [comment]
Thanks for the suggestion, they might be sharding or not using those domains anymore, since our system is fully automated, we cannot add domains manually. If our system sees them they will for sure be added. We will consider adding more harvester all around the globe, so in case they shard we capture them.
