### ISSUE TITLE
Broken domain stats?

### ISSUE THREAD

**Issue by BelleNottelling** [7c/fakefilter#82]
Hi there, I just found the project and it's honestly really promising!

Just a quick question, but I couldn't help but noticing that your chart lists a wildly different from what I got myself after pulling the database. Specifically, after removing empty lines and comments I was left 16,801 domains the DB VS the ~4,500 that's shown in the chart. Not sure if it's bugged or just counting it in a **very** different method.

Additionally, I'd love to know what the whitelist actually is and if the collection aspect of the project is open source or if it's only the JS interface you've created. Thanks!

**Comment by 7c** [comment]
Thanks, i have updated the stats with more accurate version. Some domains are shared among different providers. In the main graph we show unique known domains across all providers. You will more likely have more domains in the json. Since today we have adapted the #6 methodology to expire domains. Since today you will see less domains than probably our main charts, because json/txt will only have not-yet-expired domains.

Some providers might indeed trick us and inject popuplar email providers to sabotage, the whitelist is made against this. We can add more providers at #9 . We collect those with tools we are trying to enhance.
