### ISSUE TITLE
Add hide my email provider

### ISSUE THREAD

**Issue by ghost** [7c/fakefilter#83]
Please add icloud.com as a listed domain.

This domain provides users the ability to generate unique, random email addresses with Hide My Email. The service advertises: "you don’t have to share your real email address when filling out a form on the web or signing up for a newsletter."

This purpose is incompatible with the goal of the project which states: "We want that site owners use this repo as reliable source to find out all fake/temp provider registration attempts."

"_Mail sent to your random addresses is forwarded to your personal email account: your iCloud Mail address or any email address associated with your [Apple ID]. When you reply to an email, your personal email address remains private. The email appears as if it were sent from the Hide My Email address._"

Read more here: https://support.apple.com/guide/icloud/what-you-can-do-with-icloud-and-hide-my-email-mme38e1602db/icloud

**Comment by nullbadger** [comment]
@SecurityFighter, from both your links. It appears Apple is using the icloud domain to provide a service facilitating fake/temp registrations as well as static addresses. Since the service provides temporary email addresses, the domain should be included for that reason as this is the stated purpose of the project. Those wishing to whitelist the temporary email provider could always choose to do so. 

<img width="1029" alt="Screenshot 2023-12-06 at 19 03 41" src="https://github.com/7c/fakefilter/assets/152968110/332df799-581d-4045-8a78-42f890b725cf">
